module.exports = {
  Arpad: {
    male: [
      'Agoston',
      'Arpad',
      'Attila',
      'Bognar',
      'Denes',
      'Edmond',
      'Erno',
      'Etele',
      'Ferdinand',
      'Florian',
      'Geza',
      'Gyula',
      'Hugo',
      'Karcsi',
      'Konrad',
      'Lazlo',
      'Lukas',
      'Marko',
      'Miklos',
      'Peti',
      'Robi',
      'Tamas',
      'Ronold',
      'Viktor',
      'Zoltan',
    ],
    female: [
      'Abigel',
      'Aliz',
      'Amalia',
      'Andrea',
      'Aranka',
      'Csilla',
      'Edit',
      'Erzebet',
      'Gertrud',
      'Greta',
      'Iren',
      'Kamilla',
      'Lara',
      'Lia',
      'Lujza',
      'Matild',
      'Olga',
      'Otilia',
      'Panna',
      'Roza',
      'Terez',
      'Tunda',
      'Valeria',
      'Vilma',
      'Viola',
    ],
    steading: [
      'Aldott',
      'Almahid',
      'Elesett',
      'Feketz',
      'Godor',
      'Kelegaz',
      'Kigyov',
      'Kiralokas',
      'Kiralsir',
      'Magziklar',
      'Mocsar',
      'Nagyvros',
      'Okorm',
      'Orkfal',
      'Perov',
      'Soterdo',
      'Tehenvar',
      'Toron',
      'Torott',
      'Utolszer',
      'Valavolg',
      'Vastar',
      'Viz',
      'Volgyom',
      'Zoldom',
    ],
    mount: [
      'Barat',
      'Barsony',
      'Edesem',
      'Egatz',
      'Eso',
      'Fakyla',
      'Feketsor',
      'Felho',
      'Flotta',
      'Gazda',
      'Hold',
      'Igaslo',
      'Ijeda',
      'Koszalo',
      'Megmento',
      'Napfen',
      'Rozsa',
      'Szamla',
      'Szellem',
      'Szeplok',
      'Szerence',
      'Tusko',
      'Vad',
      'Vihar',
      'Villam',
    ]
  },
  Oloru: {
    male: [
      'Adibemi',
      'Aboye',
      'Adegoke',
      'Ayokunle',
      'Babajide',
      'Babatunde',
      'Enitan',
      'Femi',
      'Kayin',
      'Kayo',
      'de Lanre',
      'Lekan',
      'Mongo',
      'Nwachukwu',
      'Oban',
      'Ogun',
      'Olukayo',
      'de Oluwalanni',
      'Oluwatoke',
      'Onipede',
      'Sijuade',
      'Toben',
      'Utiba',
      'Zaki',
      'Zoputan',
    ],
    female: [
      'Abeni',
      'Ade',
      'Alaba',
      'Bolanle',
      'Bosade',
      'Daraja',
      'Fari',
      'Gbemisola',
      'Ife',
      'Ige',
      'Lewa',
      'Mojisola',
      'Monifa',
      'Olufemi',
      'Omolara',
      'Oni',
      'Orisa',
      'Osa',
      'Ronke',
      'Shanum',
      'Simisola',
      'Titlayo',
      'Yejide',
      'Yewande',
      'Zauna',
    ],
    steading: [
      'Asala Ilu',
      'Atijo Ina',
      'Bajesia',
      'Dudu Olomi',
      'Ebutte Meta',
      'Ejodo',
      'Esukale',
      'Fadormi',
      'Funfumi',
      'Gooluna',
      'Ijisofo',
      'Ikukenu',
      'Iwin Ago',
      'Jinibi',
      'Oba Ile',
      'Oduroke',
      'Ogbinibi',
      'Ogunibi',
      'Okanigi',
      'Okutasibo',
      'Olorusura',
      'Olusajeki',
      'Oluwakaji',
      'Opolokuta',
      'Opoligi',
    ],
    mount: [
      'Adiitu',
      'Alayo',
      'Atale',
      'Bilu',
      'Dudupatak',
      'Egun',
      'Eniyan',
      'Esirun',
      'Fenuko',
      'Funfungo',
      'Gunirun',
      'Imole',
      'Imole Uju',
      'Ira',
      'Itan',
      'Iyebiye',
      'Lulu',
      'Nilera',
      'Ogbo',
      'Ogboju',
      'Ojiji',
      'Olooto',
      'Orisa',
      'Orun',
      'Sare',
    ]
  },
  Valkoina: {
    male: [
      'Aatami',
      'Armas',
      'Arsi',
      'Arvi',
      'Eetu',
      'Hannu',
      'Heimo',
      'Ilkka',
      'Jorma',
      'Kaapo',
      'Kain',
      'Kauko',
      'Lari',
      'Manu',
      'Nuutti',
      'Petri',
      'Raimo',
      'Reima',
      'Risto',
      'Sakari',
      'Sampsa',
      'Seppo',
      'Taito',
      'Terho',
      'Vilppu',
    ],
    female: [
      'Aija',
      'Aina',
      'Ainikki',
      'Heini',
      'Ilona',
      'Irja',
      'Jaana',
      'Kirsi',
      'Maija',
      'Marita',
      'Miina',
      'Mimmi',
      'Minja',
      'Mira',
      'Naemi',
      'Outi',
      'Pirjo',
      'Päivikki',
      'Riikka',
      'Saimi',
      'Suoma',
      'Suvi',
      'Tuula',
      'Vellamo',
      'Virpi',
    ],
    steading: [
      'Etuvartio',
      'Hopea Kaivos',
      'Kalapunki',
      'Kivimurri',
      'Maaginen',
      'Maki Linna',
      'Merenranta',
      'Metsästysmaat',
      'Mustakota',
      'Mä enrinne',
      'Paja',
      'Pienni Paikka',
      'Pyhä Paikka',
      'Rantakallio',
      'Rikki',
      'Suo',
      'Suosi',
      'Torni',
      'Turvapaikka',
      'Uusipunki',
      'Valkoinen Kivi',
      'Valtaistuin',
      'Vapaanki',
      'Vihreä Paikka',
      'Viimeinen Koti',
    ],
    mount: [
      'Aave',
      'Enkeli',
      'Haiva',
      'Hopea',
      'Ilmavirta',
      'Kesi',
      'Kestaba',
      'Kiukuinnen',
      'Lansiviima',
      'Luotettava',
      'Myrskyisa',
      'Nokka',
      'Noyra',
      'Pitkanena',
      'Saikki',
      'Salama',
      'Sankari',
      'Sisko',
      'Upea',
      'Vahva',
      'Valkoinen',
      'Varmaotteinen',
      'Vesuri',
      'Vinha',
      'Ystava',

    ]
  },
  Tamanarugan: {
    male: [
      'Ade',
      'Adi',
      'Amaziah',
      'Ayokunle',
      'Ary',
      'Bambang',
      'Bima',
      'Budi',
      'Darma',
      'Dian',
      'Eli',
      'Gunardi',
      'Hartono',
      'Irwan',
      'Lauwita',
      'Manusama',
      'Okan',
      'Onesimus',
      'Sammin',
      'Tameem',
      'Tanaya',
      'Tirto',
      'Wiryono',
      'Yandi',
      'Zebulun',
    ],
    female: [
      'Adah',
      'Bulan',
      'Candrakusuma',
      'Devi',
      'Hanjojo',
      'Iman',
      'Intan',
      'Laksmini',
      'Lestari',
      'Limijanto',
      'Marah',
      'Megawati',
      'Melati',
      'Nadiyya',
      'Ophrah',
      'Ramza',
      'Sapphiral',
      'Selah',
      'Suminten',
      'Tamar',
      'Tanjaya',
      'Tjokro',
      'Tri',
      'Wangi',
      'Zenze'
    ],
    steading: [
      'Airdib',
      'Airjinh',
      'Akhir Jalan',
      'Berdarah',
      'Bidang Bera',
      'Candibula',
      'Ditingga',
      'Emasungai',
      'Gunung',
      'Kayu',
      'Kuil',
      'Ladang Hijau',
      'Lembah',
      'Menjau',
      'Ngarai',
      'Persimpangan',
      'Puncakit',
      'Sungairac',
      'Teibing',
      'Tempat Aman',
      'Tempat Istir',
      'Terkutuk',
      'Tersentu',
      'Wahah',
      'Yangtinggi',
    ],
    mount: [
      'Anginu',
      'Api',
      'Bakat',
      'Bakti',
      'Beruntung',
      'Bilah',
      'Biru',
      'Gemetar',
      'Guntur',
      'Hidungi',
      'Janda',
      'Kakicerah',
      'Kakiring',
      'Keriangan',
      'Kunang',
      'Lapar',
      'Murni',
      'Paruh',
      'Penebus',
      'Penyelemat',
      'Prajurit',
      'Rusak',
      'Satucep',
      'Setia',
      'Tahanla',
    ]
  },
};
